log4j.rootLogger=TRACE, FILE_LOGGER
log4j.appender.FILE_LOGGER=org.apache.log4j.FileAppender
log4j.appender.FILE_LOGGER.file=logs/trace.txt
log4j.appender.FILE_LOGGER.layout=org.apache.log4j.PatternLayout
log4j.appender.FILE_LOGGER.layout.ConversionPattern=%m%n